# Generated by Django 4.2.16 on 2024-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_history_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='object_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
