# Generated by Django 4.2.16 on 2024-12-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
